apiVersion: core.choreo.dev/v1alpha1
kind: Component
metadata:
  name: lumo-inventory
  projectName: ${CHOREO_PROJECT}
  description: "LUMO Inventory Management System"
spec:
  type: Web Application
  buildPack: Node.js
  runtime:
    type: nodejs
    version: "20"
  build:
    command: npm run build
  deploy:
    command: npm run start
  env:
    - name: NODE_ENV
      value: production
    - name: DATABASE_URL
      valueFrom:
        secretRef:
          name: DATABASE_URL
    - name: CLERK_SECRET_KEY
      valueFrom:
        secretRef:
          name: CLERK_SECRET_KEY
    - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
      valueFrom:
        secretRef:
          name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    - name: NEXT_PUBLIC_APP_VERSION
      value: ${GITHUB_SHA}
  resources:
    cpu:
      units: 1.0
    memory:
      units: 1.0Gi
  scaling:
    minReplicas: 1
    maxReplicas: 3
  healthCheck:
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 20
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
  expose:
    type: HTTP
    port: 3000 